# Generated by Django 4.2.30 on 2026-04-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_github_link_profile_leetcode_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_terminal_lines',
            field=models.TextField(default='> whoami\\nSoftware Developer\\n> status\\nBuilding awesome things\\n> _', help_text='Lines for the about terminal animation, separated by newlines.'),
        ),
    ]
