# Generated by Django 4.2.30 on 2026-04-19 16:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_about_terminal_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
