# Generated by Django 4.2.30 on 2026-04-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_experience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='leetcodestats',
            name='leetcode_username',
            field=models.CharField(blank=True, help_text='LeetCode username for activity graph embed', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email shown in Contact & Footer', max_length=254, null=True),
        ),
    ]
