# Generated by Django 4.2.30 on 2026-04-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_email_to_profile_leetcode_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="leetcodestats",
            name="current_streak",
            field=models.IntegerField(default=0, help_text="Current streak in days"),
        ),
        migrations.AddField(
            model_name="leetcodestats",
            name="max_streak",
            field=models.IntegerField(default=0, help_text="Maximum streak in days"),
        ),
        migrations.AddField(
            model_name="leetcodestats",
            name="total_active_days",
            field=models.IntegerField(default=0, help_text="Total active days"),
        ),
        migrations.AddField(
            model_name="leetcodestats",
            name="total_submissions",
            field=models.IntegerField(
                default=0, help_text="Total submissions in the past year"
            ),
        ),
    ]
