# Generated by Django 4.2.30 on 2026-05-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_profile_resume_alter_project_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LeetCodeStats",
        ),
    ]
