# Generated by Django 4.2.30 on 2026-05-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_delete_leetcodestats"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="card_1_text",
            field=models.CharField(default="1,200+ commits this year", max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="card_1_title",
            field=models.CharField(default="Coding Activity", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="card_2_text",
            field=models.CharField(default="Full Stack & Web Apps", max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="card_2_title",
            field=models.CharField(default="Main Specialty", max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="card_3_text",
            field=models.CharField(
                default="Building next-gen AI tools", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="card_3_title",
            field=models.CharField(default="Current Status", max_length=100),
        ),
    ]
