# Generated by Django 4.2.30 on 2026-05-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_profile_card_1_text_profile_card_1_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="card_1_text",
            field=models.CharField(
                default="Django, React, & System Design", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="card_1_title",
            field=models.CharField(default="Currently Learning", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="card_2_text",
            field=models.CharField(
                default="Premium Agentic Portfolio App", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="card_2_title",
            field=models.CharField(default="Working On", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="card_3_text",
            field=models.CharField(
                default="High Performance Web Architectures", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="card_3_title",
            field=models.CharField(default="Focused On", max_length=100),
        ),
    ]
