# Generated by Django 4.2.30 on 2026-05-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_profile_card_1_text_alter_profile_card_1_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                db_index=True, help_text="e.g., Language, Framework", max_length=50
            ),
        ),
    ]
