# Generated by Django 4.2.30 on 2026-05-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_skill_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True,
                        help_text="Stores IP or Hash",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referrer", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
