# Generated by Django 4.2.30 on 2026-05-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_visitorlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorLog',
        ),
    ]
