# Generated by Django 5.2.5 on 2026-04-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="live_link",
            field=models.URLField(
                blank=True, help_text="Optional live demo URL", null=True
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("Frontend", "Frontend"),
                    ("Backend", "Backend"),
                    ("Database", "Database"),
                    ("Data", "Data"),
                    ("Tools", "Tools"),
                ],
                max_length=50,
            ),
        ),
    ]
