# Generated by Django 5.2.5 on 2026-04-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_project_live_link_alter_skill_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="Optional phone number", max_length=20, null=True
            ),
        ),
    ]
