# Generated by Django 5.2.5 on 2026-04-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "excerpt",
                    models.TextField(help_text="Short description for list view"),
                ),
                (
                    "content",
                    models.TextField(help_text="Full blog content (supports HTML)"),
                ),
                ("featured_image", models.ImageField(upload_to="blog/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
