# Generated by Django 4.2.30 on 2026-05-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(default="Engineering", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="read_time",
            field=models.CharField(default="5 min read", max_length=50),
        ),
    ]
