# Generated by Django 4.2.30 on 2026-05-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_category_post_read_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                db_index=True, default="Engineering", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
